dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8

git:
  depth: 3

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - ./.travis/setup_database

env:
  - EBEAN_DB=h2
  - EBEAN_DB=pg

install: true

script:
  - mvn clean test

after_failure:
  - ./.travis/print_surefire_reports

cache:
  directories:
  - $HOME/.m2
